In [1]:
print("Hello World, testing out jupyter notebook!")

Hello World, testing out jupyter notebook!


In [3]:
import pandas as pd
import numpy as np

In [3]:
x = np.array([1,2,3,4,5], dtype=float)
print(x)
# first numpy array

[1. 2. 3. 4. 5.]


In [4]:
print(x)

[1. 2. 3. 4. 5.]


In [5]:
p = np.array([4, 24, 5, 43, 68], dtype=float)
print(p)

[ 4. 24.  5. 43. 68.]


In [6]:
type(p)

numpy.ndarray

In [7]:
print(5*p)

[ 20. 120.  25. 215. 340.]


In [8]:
z = 5 * p
# testing out operations with numpy arrays

In [9]:
z

array([ 20., 120.,  25., 215., 340.])

In [10]:
print(z)

[ 20. 120.  25. 215. 340.]


In [11]:
np.sum(z)

720.0

In [12]:
z > 10
# returns array with booleans

array([ True,  True,  True,  True,  True])

In [13]:
z > 25

array([False,  True, False,  True,  True])

In [14]:
z[z>30]

array([120., 215., 340.])

In [15]:
print(np.pi)

3.141592653589793


In [16]:
np.log2(z)

array([4.32192809, 6.9068906 , 4.64385619, 7.74819285, 8.40939094])

In [17]:
np.log10(z)

array([1.30103   , 2.07918125, 1.39794001, 2.33243846, 2.53147892])

In [333]:
print("Experimenting with too much log....")
#np.log120(z)
# this caused an error


Experimenting with too much log....


In [19]:
# higher log values does not exist with numpy
a = pd.Series([1, 2, 3, 4, 5, 6])

In [20]:
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [21]:
type(a.values)

numpy.ndarray

In [22]:
np.sum(a.values)

21

In [23]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [24]:
print(a.index)

RangeIndex(start=0, stop=6, step=1)


In [25]:
players = pd.Series([28, 30, 27, 28], index=["Anthony Davis", "James Harden", "LeBron James", "Damian Lilliard"])
print(players)

Anthony Davis      28
James Harden       30
LeBron James       27
Damian Lilliard    28
dtype: int64


In [26]:
players[players> 28]
# the games leading scorer and 'MVP'

James Harden    30
dtype: int64

In [27]:
topscore = list(players.values)

In [28]:
topscore

[28, 30, 27, 28]

In [29]:
print(max(topscore))

30


In [30]:
print(min(topscore))

27


In [31]:
"Anthony Davis" in players

True

In [32]:
"Bob Simmons" in players

False

In [5]:
"LeBron James" in players
# more testing

True

In [4]:
players = pd.Series([28, 30, 27, 28], index=["Anthony Davis", "James Harden", "LeBron James", "Damian Lilliard"])
print(players)


Anthony Davis      28
James Harden       30
LeBron James       27
Damian Lilliard    28
dtype: int64


In [6]:
"LeBron James" in players

True

In [7]:
players[players > 28]

James Harden    30
dtype: int64

In [8]:
players[players > 27]

Anthony Davis      28
James Harden       30
Damian Lilliard    28
dtype: int64

In [9]:
elDict = {'players':["Matthew Strong", ""]}

In [10]:
elDict

{'players': ['Matthew Strong', '']}

In [11]:
elDict = {'players':["Matthew Strong", "LeBron James", "Joel Embiid", "Michael Jordan"], 'PPG':[1, 27, 20, 30], 'Team':["Baby Bobby Ballers", "Los Angeles Lakers", "Philadelphia 76ers"]}

In [12]:
elDict

{'PPG': [1, 27, 20, 30],
 'Team': ['Baby Bobby Ballers', 'Los Angeles Lakers', 'Philadelphia 76ers'],
 'players': ['Matthew Strong',
  'LeBron James',
  'Joel Embiid',
  'Michael Jordan']}

In [273]:
#data = pd.DataFrame(elDict)

In [14]:
elDict = {'players':["Matthew Strong", "LeBron James", "Joel Embiid", "Michael Jordan"], 'PPG':[1, 27, 20, 30], 'Team':["Baby Bobby Ballers", "Los Angeles Lakers", "Philadelphia 76ers", "Chicago Bulls"]}

In [15]:
elDict

{'PPG': [1, 27, 20, 30],
 'Team': ['Baby Bobby Ballers',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  'Chicago Bulls'],
 'players': ['Matthew Strong',
  'LeBron James',
  'Joel Embiid',
  'Michael Jordan']}

In [16]:
dataNBA = pd.DataFrame(elDict)

In [17]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [18]:
print(dataNBA)

   PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan


In [19]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [20]:
dataNBA.head(2)

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James

In [334]:
# (deleted)


In [22]:
playersSorted = dataNBA.sort_values(by="PPG", ascending=False)
playersSorted

PPG                Team         players
3   30       Chicago Bulls  Michael Jordan
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
0    1  Baby Bobby Ballers  Matthew Strong

In [23]:
dataNBA["PPG"] > 20

0    False
1     True
2    False
3     True
Name: PPG, dtype: bool

In [25]:
dataNBA["PPG"] > 15

0    False
1     True
2     True
3     True
Name: PPG, dtype: bool

In [26]:
p = pd.Series(dataNBA["PPG"] > 15)

In [27]:
p

0    False
1     True
2     True
3     True
Name: PPG, dtype: bool

In [272]:
dataNBA.groupby("PPG")

In [29]:
dataNBA.groupby("PPG")

In [30]:
print(dataNBA.groupby("PPG"))

In [31]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [32]:
dataNBA["PPG"]

0     1
1    27
2    20
3    30
Name: PPG, dtype: int64

In [33]:
dataNBA["PPG"].apply(lambda x: x +1)

0     2
1    28
2    21
3    31
Name: PPG, dtype: int64

In [34]:
dataNBA


PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [35]:
dataNBA["PPG"]

0     1
1    27
2    20
3    30
Name: PPG, dtype: int64

In [36]:
dataNBA["PPG"] = dataNBA["PPG"].apply(lambda x: x +1)
# testing lamba

In [37]:
dataNBA 

PPG                Team         players
0    2  Baby Bobby Ballers  Matthew Strong
1   28  Los Angeles Lakers    LeBron James
2   21  Philadelphia 76ers     Joel Embiid
3   31       Chicago Bulls  Michael Jordan

In [38]:
from sklearn import svm
# moving on to svm 

In [39]:
X = [[0,0], [2,2]]
y=[2.5, 4.5]
client = svm.SVR()
# support vector regression

In [40]:
client.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [271]:
print("More testing on the way....")

More testing on the way....


In [42]:
client.predict([[1,1]])

array([3.5])

In [43]:
client.predict([[5,5]])

array([3.50011314])

In [45]:
client.predict([[2,2]])

array([4.4])

In [46]:
vo = np.array([1, 2, 4])

In [47]:
vo


array([1, 2, 4])

In [48]:
print(vo)

[1 2 4]


In [49]:
print([1, 2, 4])

[1, 2, 4]


In [270]:
clr = svm.SVR()


In [62]:
X = [[0,0], [2,2], [3,3]]
y=[2.5, 4.5]
client = svm.SVR()

In [269]:
X=[[0,0], [1,1], [2,2]]
y=[3.5,7.5, 9.7]
client = svm.SVR()
client.fit(X,y)
#print("{} and {}".format(X,y))


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [85]:
client.predict([[3,3]])

array([7.86775603])

In [75]:
print("Hi")
# ...

Hi


In [90]:
# some simple linear regression here 
normLinear = svm.SVR(kernel="linear")
X=[[0,0], [1,1], [2,2]]
y=[3.5,7.5, 11.5]
normLinear.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [93]:
normLinear.predict([[2.5,2.5]])

array([13.35])

In [94]:
import json
import requests
# testing json and requests here

In [95]:
response = requests.get("https://jsonplaceholder.typicode.com/todos")


In [96]:
print(response)

<Response [200]>


In [340]:
#print("{} is the text of the response.".format(response.text))

In [98]:
todos = json.loads(response.text)

In [100]:
print("hi")

hi


In [104]:
todos[0]['completed']
# everything is put into dictionaries!

False

In [105]:
x = np.array([[72, 200], [70, 180], [69, 179], [80, 250], [84, 300], [81, 270]])
y = np.array(["Point Guard", "Point Guard", "Point Guard", "Center", "Center", "Center"])

In [106]:
clf = svm.SVC()
clf.fit(x, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [113]:
clf.predict([[82,190]])

array(['Center'], dtype='<U11')

In [118]:
newRep = requests.get("http://data.nba.net/10s/prod/v1/2018/players.json")

In [343]:

# print(newRep.text) ... would have printed out all of the the nba players, uncommenting and run this section to see the results.

In [121]:
allPlayers = json.loads(newRep.text)

In [341]:
#allPlayers

In [342]:
#print(allPlayers['league']['standard'])
# looking at all of the players

In [132]:
# we want to choose between G F and C
x = np.array([1,2,3])

In [140]:
x = np.append(x,[[1]])
print(x)
y = np.array([])
print(y)




[1 2 3 1 1 1 1]
[]


In [339]:
playerSize = np.array([[0,0]])
playerPosition = np.array([])
testing = np.array([])
for i in allPlayers['league']['standard']:
    skip = False
    if(i['weightPounds'] == '' or i['heightFeet']=='' or i['heightInches']==''):
        skip = True
    if(not skip):
        totalHeight = (int(i['heightFeet'])*12) + int(i['heightInches'])
        #fullName = i['firstName'] + ' ' + i['lastName']
        #print('{} is {} inches tall.'.format(fullName, totalHeight))
        #print([int(i['weightPounds']), totalHeight])
        arr = np.array([[int(i['weightPounds']), totalHeight]])
        xEr = np.array([int(i['weightPounds']), totalHeight])
        #print(arr)
        #print(i['pos'])
        #print(playerSize)
        playerSize = np.concatenate((playerSize, arr))
        testing = np.append(testing, xEr)
        #playerSize = np.append(playerSize, [int(i['weightPounds']), totalHeight])
        playerPosition = np.append(playerPosition, i['pos'])

#realPlayerSize = playerSize[playerSize!=[0,0]]
y = np.expand_dims(playerSize, axis=1)

realPlayers = playerSize[1:]
print(realPlayers)

clf = svm.SVC()

clf.fit(realPlayers, playerPosition)
#print(clf)
print(clf)
clf.predict([[260, 82]])
clf.score([[260, 82], [250, 80]], ['C', 'C'])
#score matches up what the svm thinks the answer is vs. what is actually provided to it
import matplotlib.pyplot as plt
print(testing.size)
print(playerPosition.size)

# testing out the functions



[[190  78]
 [240  79]
 [190  74]
 ...
 [250  84]
 [250  83]
 [240  85]]
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
1096
548


In [338]:
# final version

import json
import requests
from sklearn import svm
import pandas as pd
import numpy as np


# Matthew Strong CU Boulder
# July 21 2018
# NBA Data API used 
# uses SVC machine learning to predict the best position for a person who wants to see if they have 'NBA' level height and weight
# indeed the average height of a man would be very low for this function


def predictPosition():
    
    newRep = requests.get("http://data.nba.net/10s/prod/v1/2018/players.json")
    allPlayers = json.loads(newRep.text)
    # loading all of the players into python dictionary with the data nba api
    playerSize = np.array([[0,0]])
    # setting the numpu arrays
    playerPosition = np.array([])
    for i in allPlayers['league']['standard']:
        skip = False
        if(i['weightPounds'] == '' or i['heightFeet']=='' or i['heightInches']==''):
            skip = True
            # if a weight or height aspect of the player is visibly missing, skip the player
        if(not skip):
            # calculates total height
            totalHeight = (int(i['heightFeet'])*12) + int(i['heightInches'])
            #fullName = i['firstName'] + ' ' + i['lastName']
            #print('{} is {} inches tall.'.format(fullName, totalHeight))
            #print([int(i['weightPounds']), totalHeight])
            
            # array of the weight and full height
            arr = np.array([[int(i['weightPounds']), totalHeight]])
            #print(arr)
            #print(playerSize)
            # adding the height and weight duo to the np array of every player
            playerSize = np.concatenate((playerSize, arr))
            #playerSize = np.append(playerSize, [int(i['weightPounds']), totalHeight])
            
            #adding player position here to array -
            # options are center, forward, or guard or combo of any two except guard-center
            playerPosition = np.append(playerPosition, i['pos'])   
    # getting rid of the [0,0] placeholder
    realPlayers = playerSize[1:]
    #print(realPlayers)
    clf = svm.SVC()
    # new instance of svc
    # fit array of player's weight/heights to their corresponding position
    clf.fit(realPlayers, playerPosition)         
    weight = 0
    heightFeet = 0
    heightInches = 0
    # the next few while loops will get the user's height and weight and will check for failure to convert to int
    # e.g. the user types in 'swol' for weight
    while(1):
        weight = input("What is your weight in pounds? ")
        try:
            weight = int(weight)
            break
        except ValueError:
            print("Please enter in a number! ")
    while(1):
        heightFeet = input("What is your height? Enter feet first. ")
        try:
            heightFeet = int(heightFeet)
            
            break
        except ValueError:
            print("Please enter in a number! ")
    while(1):
        heightInches = input("What is your height? Now enter inches. ")
        try:
            heightInches = int(heightInches)
            break
        except ValueError:
            print("Please enter in a number!")
    totalHeight = (heightFeet*12) + heightInches
    # predicts the user's classification based on weight and height and reads the position referencing a dictionary
    rest = clf.predict([[weight, totalHeight]])
    #print(rest[0])
    myDict = {'F':"Forward", 'G':'Guard', 'C':"Center", 'G-F':"Primary Guard and Secondary Forward", 'F-G':"Primary Forward and Secondary Guard", 'F-C':"Primary Forward and Secondary Center", 'C-F':"Primary Center and Secondary Forward"}
    selection = myDict[rest[0]]
    print("Based on the Stats of ALL of the NBA Players, and your height and weight, you should be a {}.".format(selection))
    #print("{} is the weight".format(weight))
    #print("{} is the height in feet".format(heightFeet))
    #print("{} is the height in inches".format(heightInches))
# press shift+enter to run this section of code as well as the function

predictPosition()


What is your weight in pounds? 260
What is your height? Enter feet first. 7
What is your height? Now enter inches. 1
Based on the Stats of ALL of the NBA Players, and your height and weight, you should be a Center.


In [332]:
x = np.array([["run", "bike", "swim"], ["sit", "watch", "lie"]])
print(x.shape)
print("{1} is the second option, and {0} is the first option".format("run", "bike"))
# testing strings

(2, 3)
bike is the second option, and run is the first option
